apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "ebs-sc"   # Make sure ebs-sc exists
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    purpose: "ebs-dynamic-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c   # Ensure your StorageClass provisions in same AZ
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-dynamic-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-dynamic-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dynamic
spec:
  type: LoadBalancer
  selector:
    purpose: "ebs-dynamic-demo"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
