apiVersion: v1 
kind: Pod 
metadata: 
  name: lables 
  lables: 
    project: expense 
    component: backend 
    environment: dev 
spec: 
  containers: 
  - name: nginx 
    image: nginx 