apiVersion: v1 
kind: Pod 
metadata: 
  name: annotations 
  annotations: 
    buildURL: "https://jenkins.com/expense/backend/23"
    imageregistry: "https://hub.docker.com/"
spec: 
  containers: 
  - name: nginx 
    image: nginx 