apiVersion: v1
kind: Pod
metadata:
  name: resources-and-limits
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # soft limit 
      requests:
        memory: "60Mi"
        cpu: "100m"
      # hard limit 
      limits:
        memory: "128Mi"
        cpu: "150m"
