apiVersion: v1
kind: Pod
metadata:
  name: nginx-node
  labels:
    project: expense
    environment: dev
    component: backend
    version: "1.0.0"
    demo: nodeport
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
    component: backend
    version: "1.0.0"
    demo: nodeport
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
