apiVersion: v1 
kind: Service 
metadata: 
  name: node-port 
spec: 
  type: NodePort
  selector: 
    project: expense 
    environment: dev 
    componet: backend 
    version: "1.0.0"
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 

--- 
apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx 
  labels:
    project: expense 
    environemt: dev 
    component: backend
    version: "1.0.0"
spec: 
  containers: 
  - name: nginx 
    image: nginx 

    
