apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-load-balancer 
spec: 
  type: LoadBalancer 
  selector: 
    porject: expense 
    environment: dev 
    component: backend 
    demo: load-balancer 
    version: "1.0.0"
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 

--- 

apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-lb 
  labels: 
   porject: expense 
   environment: dev 
   component: backend 
   demo: load-balancer 
   version: "1.0.0" 
spec: 
  containers: 
  - name: nginx
    image: nginx 